const Data = [
    {
        id: 1,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/trendy-small-digital-agency.jpg',
        title: 'Trendy Small Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'SMALL AGENCY',
    },
    {
        id: 2,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/illustrated-small-digital-agency.jpg',
        title: 'Illustrated Small Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'OPEN PAGE',
    },
    {
        id: 3,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/modern-small-digital-agency.jpg',
        title: 'Modern Small Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'SMALL AGENCY',
    },
    {
        id: 4,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/classic-small-digital-agency.jpg',
        title: 'Classic Small Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'SMALL AGENCY',
    },
    {
        id: 5,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/trendy-big-digital-agency.jpg',
        title: 'Trendy Big Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'BIG AGENCY',
    },
    {
        id: 6,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/modern-big-digital-agency.jpg',
        title: 'Modern Big Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'BIG AGENCY',
    },
    {
        id: 7,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/classic-big-digital-agency.jpg',
        title: 'Classic Big Digital Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'BIG AGENCY',
    },
    {
        id: 8,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/trendy-one-page.jpg',
        title: 'Trendy One Page Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'OPEN PAGE',
    },
    {
        id: 9,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/illustrated-one-page-agency.jpg',
        title: 'Illustrated One Page Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'OPEN PAGE',
    },
    {
        id: 10,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/modern-one-page-agency.jpg',
        title: 'Modern One Page Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'OPEN PAGE',
    },
    {
        id: 11,
        image: 'https://new.axilthemes.com/demo/template/splash/cynic/images/templates/classic-one-page-agency.jpg',
        title: 'Classic One Page Agency',
        details: 'For big digital agencies that offer basic services to its clients.',
        category: 'OPEN PAGE',
    },
];

export default Data;